# This file contains the configuration settings for your Redwood app.
# This file is also what makes your Redwood app a Redwood app.
# If you remove it and try to run `yarn rw dev`, you'll get an error.
#
# For the full list of options, see the "App Configuration: redwood.toml" doc:
# https://redwoodjs.com/docs/app-configuration-redwood-toml

[web]
  host = "0.0.0.0"
  title = "Redwood App"
  port = "${PORT:8913}"
  apiUrl = "/api"
  includeEnvironmentVariables = [
      "SUPABASE_URL",
      "SUPABASE_KEY",
      ]
[api]
  host = "0.0.0.0"
  port = "${PORT:8915}"
[browser]
  open = true
[notifications]
  versionUpdates = ["latest"]
